In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/CustomerChurn.csv")
df.head()

,LoyaltyID,Customer ID,Senior Citizen,Partner,Dependents,Tenure,Phone Service,Multiple Lines,Internet Service,Online Security,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn
0,318537,7590-VHVEG,No,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,152148,5575-GNVDE,No,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,326527,3668-QPYBK,No,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,845894,7795-CFOCW,No,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,503388,9237-HQITU,No,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   LoyaltyID          7043 non-null   int64
 1   Customer ID        7043 non-null   str
 2   Senior Citizen     7043 non-null   str
 3   Partner            7043 non-null   str
 4   Dependents         7043 non-null   str
 5   Tenure             7043 non-null   int64
 6   Phone Service      7043 non-null   str
 7   Multiple Lines     7043 non-null   str
 8   Internet Service   7043 non-null   str
 9   Online Security    7043 non-null   str
 10  Online Backup      7043 non-null   str
 11  Device Protection  7043 non-null   str
 12  Tech Support       7043 non-null   str
 13  Streaming TV       7043 non-null   str
 14  Streaming Movies   7043 non-null   str
 15  Contract           7043 non-null   str
 16  Paperless Billing  7043 non-null   str
 17  Payment Method     7043 non-null   str
 18  Monthly Charges    7043 non-null   float64
 19  Total Charges      7043 non-null   str
 20  Churn              7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [7]:
df.isnull().sum()

LoyaltyID            0
Customer ID          0
Senior Citizen       0
Partner              0
Dependents           0
Tenure               0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
Churn                0
dtype: int64

In [5]:
df.describe()

           LoyaltyID       Tenure  Monthly Charges
count    7043.000000  7043.000000      7043.000000
mean   550382.651001    32.371149        64.761692
std    260776.118690    24.559481        30.090047
min    100346.000000     0.000000        18.250000
25%    323604.500000     9.000000        35.500000
50%    548704.000000    29.000000        70.350000
75%    776869.000000    55.000000        89.850000
max    999912.000000    72.000000       118.750000

In [6]:
df['Churn'].value_counts()
df['Churn'].value_counts(normalize = True)*100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [8]:
# as total charges is in str form we need to change them to numeric 
pd.to_numeric(df['Total Charges'],errors ='coerce').isnull().sum()

np.int64(11)

In [10]:
# let's investugste the 11 null rows before altering anything
mask = pd.to_numeric(df['Total Charges'],errors = 'coerce').isnull()
df[mask][['Customer ID','Tenure','Monthly Charges','Total Charges']]

     Customer ID  Tenure  Monthly Charges Total Charges
488   4472-LVYGI       0            52.55
753   3115-CZMZD       0            20.25
936   5709-LVOEQ       0            80.85
1082  4367-NUYAO       0            25.75
1340  1371-DWPAZ       0            56.05
3331  7644-OMVMY       0            19.85
3826  3213-VVOLG       0            25.35
4380  2520-SGTTA       0            20.00
5218  2923-ARZLG       0            19.70
6670  4075-WKNIU       0            73.35
6754  2775-SEFEE       0            61.90

# We found that the 11 null rows are all new customers so this is not any error ,the customers are new that's why thay are not billed yet

In [12]:
df['Total Charges']=pd.to_numeric(df['Total Charges'],errors ='coerce')
df['Total Charges']=df['Total Charges'].fillna(0)

In [13]:
print("Missing values now:", df['Total Charges'].isnull().sum())
print("Dtype now:", df['Total Charges'].dtype)
df.loc[[488, 753, 936], ['Customer ID', 'Tenure', 'Total Charges']]

Missing values now: 0
Dtype now: float64

    Customer ID  Tenure  Total Charges
488  4472-LVYGI       0            0.0
753  3115-CZMZD       0            0.0
936  5709-LVOEQ       0            0.0

In [1]:
import pandas as pd

demographics = pd.read_csv("../data/enrichment/Telco_customer_churn_demographics.csv")
location = pd.read_csv("../data/enrichment/Telco_customer_churn_location.csv")
services = pd.read_csv("../data/enrichment/Telco_customer_churn_services.csv")
status = pd.read_csv("../data/enrichment/Telco_customer_churn_status.csv")
population = pd.read_csv("../data/enrichment/Telco_customer_churn_population.csv")

for name, d in [("demographics", demographics), ("location", location),
                ("services", services), ("status", status), ("population", population)]:
    print(name, "-> shape:", d.shape)
    print(d.columns.tolist())
    print()

demographics -> shape: (7043, 9)
['Customer ID', 'Count', 'Gender', 'Age', 'Under 30', 'Senior Citizen', 'Married', 'Dependents', 'Number of Dependents']

location -> shape: (7043, 10)
['Location ID', 'Customer ID', 'Count', 'Country', 'State', 'City', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude']

services -> shape: (7043, 31)
['Service ID', 'Customer ID', 'Count', 'Quarter', 'Referred a Friend', 'Number of Referrals', 'Tenure in Months', 'Offer', 'Phone Service', 'Avg Monthly Long Distance Charges', 'Multiple Lines', 'Internet Service', 'Internet Type', 'Avg Monthly GB Download', 'Online Security', 'Online Backup', 'Device Protection Plan', 'Premium Tech Support', 'Streaming TV', 'Streaming Movies', 'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds', 'Total Extra Data Charges', 'Total Long Distance Charges', 'Total Revenue']

status -> shape: (7043, 12)
['Status ID', 'Customer ID', 'Count', 'Quarter', 'Satisfaction Score', 'Customer Status', 'Churn Label', 'Churn Value', 'Churn Score', 'CLTV', 'Churn Category', 'Churn Reason']

population -> shape: (1671, 3)
['ID', 'Zip Code', 'Population']

In [2]:
# Cell — load main dataset fresh in this notebook
df = pd.read_csv("../data/raw/CustomerChurn.csv")

# Fix Total Charges again (this notebook is separate, so redo the Week 2 fix)
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce').fillna(0)

print("Main df shape before merge:", df.shape)

Main df shape before merge: (7043, 21)

In [3]:
# Cell — merge demographics, keeping only new columns
demo_cols = demographics[['Customer ID', 'Age', 'Married', 'Number of Dependents']]

df = df.merge(demo_cols, on='Customer ID', how='left')
print("Shape after demographics merge:", df.shape)
df[['Customer ID', 'Age', 'Married', 'Number of Dependents']].head()

Shape after demographics merge: (7043, 24)

  Customer ID  Age Married  Number of Dependents
0  7590-VHVEG   36     Yes                     0
1  5575-GNVDE   46      No                     0
2  3668-QPYBK   37      No                     0
3  7795-CFOCW   53      No                     0
4  9237-HQITU   19      No                     2

In [4]:
print("Shape after demographics merge:", df.shape)

Shape after demographics merge: (7043, 24)

In [5]:
# Cell — merge status, keeping only new/valuable columns
status_cols = status[['Customer ID', 'Satisfaction Score', 'CLTV', 'Churn Category', 'Churn Reason']]

df = df.merge(status_cols, on='Customer ID', how='left')
print("Shape after status merge:", df.shape)
df[['Customer ID', 'Satisfaction Score', 'CLTV', 'Churn Category', 'Churn Reason']].head()

Shape after status merge: (7043, 28)

,Customer ID,Satisfaction Score,CLTV,Churn Category,Churn Reason
0,7590-VHVEG,3,3964,NaN,NaN
1,5575-GNVDE,3,3441,NaN,NaN
2,3668-QPYBK,1,3239,Competitor,Competitor made better offer
3,7795-CFOCW,3,4307,NaN,NaN
4,9237-HQITU,2,2701,Other,Moved

In [6]:
# Cell — merge location, keeping only Zip Code
location_cols = location[['Customer ID', 'Zip Code']]

df = df.merge(location_cols, on='Customer ID', how='left')
print("Shape after location merge:", df.shape)
df[['Customer ID', 'Zip Code']].head()

Shape after location merge: (7043, 29)

  Customer ID  Zip Code
0  7590-VHVEG     90001
1  5575-GNVDE     90002
2  3668-QPYBK     90003
3  7795-CFOCW     90004
4  9237-HQITU     90005

In [7]:
# Cell — merge population via Zip Code
pop_cols = population[['Zip Code', 'Population']]

df = df.merge(pop_cols, on='Zip Code', how='left')
print("Shape after population merge:", df.shape)
df[['Customer ID', 'Zip Code', 'Population']].head()

Shape after population merge: (7043, 30)

  Customer ID  Zip Code Population
0  7590-VHVEG     90001     54,492
1  5575-GNVDE     90002     44,586
2  3668-QPYBK     90003     58,198
3  7795-CFOCW     90004     67,852
4  9237-HQITU     90005     43,019

In [8]:
# Cell — final structure check
print(df.shape)
df.info()

(7043, 30)
<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   LoyaltyID             7043 non-null   int64
 1   Customer ID           7043 non-null   str
 2   Senior Citizen        7043 non-null   str
 3   Partner               7043 non-null   str
 4   Dependents            7043 non-null   str
 5   Tenure                7043 non-null   int64
 6   Phone Service         7043 non-null   str
 7   Multiple Lines        7043 non-null   str
 8   Internet Service      7043 non-null   str
 9   Online Security       7043 non-null   str
 10  Online Backup         7043 non-null   str
 11  Device Protection     7043 non-null   str
 12  Tech Support          7043 non-null   str
 13  Streaming TV          7043 non-null   str
 14  Streaming Movies      7043 non-null   str
 15  Contract              7043 non-null   str
 16  Paperless Billing     7043 non-null   str
 17  Payment Method        7043 non-null   str
 18  Monthly Charges       7043 non-null   float64
 19  Total Charges         7043 non-null   float64
 20  Churn                 7043 non-null   str
 21  Age                   7043 non-null   int64
 22  Married               7043 non-null   str
 23  Number of Dependents  7043 non-null   int64
 24  Satisfaction Score    7043 non-null   int64
 25  CLTV                  7043 non-null   int64
 26  Churn Category        1869 non-null   str
 27  Churn Reason          1869 non-null   str
 28  Zip Code              7043 non-null   int64
 29  Population            7043 non-null   str
dtypes: float64(2), int64(7), str(21)
memory usage: 1.6 MB

In [9]:
# Cell — check for any unexpected new nulls introduced by merging
df.isnull().sum()

LoyaltyID                  0
Customer ID                0
Senior Citizen             0
Partner                    0
Dependents                 0
Tenure                     0
Phone Service              0
Multiple Lines             0
Internet Service           0
Online Security            0
Online Backup              0
Device Protection          0
Tech Support               0
Streaming TV               0
Streaming Movies           0
Contract                   0
Paperless Billing          0
Payment Method             0
Monthly Charges            0
Total Charges              0
Churn                      0
Age                        0
Married                    0
Number of Dependents       0
Satisfaction Score         0
CLTV                       0
Churn Category          5174
Churn Reason            5174
Zip Code                   0
Population                 0
dtype: int64

In [10]:
# Cell — save the merged, cleaned dataset
df.to_csv("../data/processed_customer_churn.csv", index=False)
print("Saved:", df.shape)

Saved: (7043, 30)

In [11]:
# Cell — fix Population dtype
df['Population'] = df['Population'].str.replace(',', '').astype(int)
print(df['Population'].dtype)
df['Population'].describe()

int64

count      7043.000000
mean      22139.814568
std       21152.174407
min          11.000000
25%        2344.000000
50%       17554.000000
75%       36125.000000
max      105285.000000
Name: Population, dtype: float64

In [12]:
df.to_csv("../data/processed_customer_churn.csv", index=False)
print("Re-saved with Population fixed:", df.shape)

Re-saved with Population fixed: (7043, 30)

In [13]:
print(df['Population'].dtype)

int64